"""Add setup fields to condominiums

Revision ID: a916ecf0a2f3
Revises: 63276e845679
Create Date: 2026-02-06 13:13:47.048030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a916ecf0a2f3'
down_revision: Union[str, None] = '63276e845679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condominiums', sa.Column('default_monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('condominiums', sa.Column('is_setup_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condominiums', 'is_setup_completed')
    op.drop_column('condominiums', 'default_monthly_fee')
    # ### end Alembic commands ###
